tasks:
  - name: mpi
    init: > 
      sudo apt update && sudo apt upgrade -y && sudo apt install mpich libmpich-dev -y
  - name: cargo
    init: gp sync-await mpi && cargo build
    command: cargo run -- --path assets/graph.json

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - tamasfe.even-better-toml

